const jobsData = [
    {
      id: 1,
      title: 'Frontend Developer',
      company: 'Tech Solutions Inc.',
      location: 'New York, NY',
      type: 'Full-Time',
      domain: 'Software Development',
      description: 'We are looking for a skilled Frontend Developer to join our team.',
    },
    {
      id: 2,
      title: 'Backend Developer',
      company: 'Innovative Tech',
      location: 'San Francisco, CA',
      type: 'Part-Time',
      domain: 'Software Development',
      description: 'Join our backend team to develop and maintain web applications.',
    },
    {
      id: 3,
      title: 'Data Scientist',
      company: 'Data Insights',
      location: 'Chicago, IL',
      type: 'Full-Time',
      domain: 'Data Science',
      description: 'Analyze large datasets to gain actionable insights.',
    },
    {
      id: 4,
      title: 'UX/UI Designer',
      company: 'Creative Minds',
      location: 'Austin, TX',
      type: 'Full-Time',
      domain: 'Design',
      description: 'Design intuitive and visually appealing user interfaces.',
    },
    {
      id: 5,
      title: 'Project Manager',
      company: 'Business Solutions',
      location: 'Seattle, WA',
      type: 'Full-Time',
      domain: 'Management',
      description: 'Oversee project timelines and ensure deliverables are met.',
    },
    // Add more job entries here...
    {
      id: 6,
      title: 'Digital Marketing Specialist',
      company: 'Marketing Gurus',
      location: 'Boston, MA',
      type: 'Part-Time',
      domain: 'Marketing',
      description: 'Plan and execute digital marketing campaigns.',
    },
    {
      id: 7,
      title: 'Sales Representative',
      company: 'Sales Pros',
      location: 'Denver, CO',
      type: 'Full-Time',
      domain: 'Sales',
      description: 'Drive sales and build relationships with clients.',
    },
    {
      id: 8,
      title: 'HR Manager',
      company: 'People First',
      location: 'Miami, FL',
      type: 'Full-Time',
      domain: 'Human Resources',
      description: 'Manage recruitment and employee relations.',
    },
    {
      id: 9,
      title: 'Network Engineer',
      company: 'NetTech',
      location: 'Dallas, TX',
      type: 'Full-Time',
      domain: 'IT',
      description: 'Maintain and optimize network infrastructure.',
    },
    {
      id: 10,
      title: 'Financial Analyst',
      company: 'Finance Experts',
      location: 'Atlanta, GA',
      type: 'Full-Time',
      domain: 'Finance',
      description: 'Analyze financial data to support business decisions.',
    },
    {
      id: 11,
      title: 'Software Tester',
      company: 'Quality Assurance Co.',
      location: 'San Jose, CA',
      type: 'Contract',
      domain: 'Software Testing',
      description: 'Test software applications for bugs and issues.',
    },
    {
      id: 12,
      title: 'Content Writer',
      company: 'Content Creators',
      location: 'Portland, OR',
      type: 'Part-Time',
      domain: 'Content Writing',
      description: 'Create engaging content for various platforms.',
    },
    {
      id: 13,
      title: 'Product Manager',
      company: 'Product Innovators',
      location: 'Los Angeles, CA',
      type: 'Full-Time',
      domain: 'Product Management',
      description: 'Lead product development from ideation to launch.',
    },
    {
      id: 14,
      title: 'Graphic Designer',
      company: 'Design Studio',
      location: 'San Diego, CA',
      type: 'Freelance',
      domain: 'Design',
      description: 'Create visual content for marketing materials.',
    },
    {
      id: 15,
      title: 'Operations Manager',
      company: 'Operations Experts',
      location: 'Houston, TX',
      type: 'Full-Time',
      domain: 'Operations',
      description: 'Oversee daily operations and ensure efficiency.',
    },
    {
      id: 16,
      title: 'Customer Support Specialist',
      company: 'Customer First',
      location: 'Phoenix, AZ',
      type: 'Full-Time',
      domain: 'Customer Support',
      description: 'Provide support to customers and resolve issues.',
    },
    {
      id: 17,
      title: 'Business Analyst',
      company: 'Business Solutions',
      location: 'Philadelphia, PA',
      type: 'Full-Time',
      domain: 'Business Analysis',
      description: 'Analyze business processes and recommend improvements.',
    },
    {
      id: 18,
      title: 'IT Support Technician',
      company: 'Tech Support',
      location: 'San Antonio, TX',
      type: 'Full-Time',
      domain: 'IT',
      description: 'Provide technical support to end-users.',
    },
    {
      id: 19,
      title: 'Social Media Manager',
      company: 'Social Media Experts',
      location: 'Charlotte, NC',
      type: 'Full-Time',
      domain: 'Marketing',
      description: 'Manage social media accounts and campaigns.',
    },
    {
      id: 20,
      title: 'SEO Specialist',
      company: 'SEO Pros',
      location: 'Orlando, FL',
      type: 'Full-Time',
      domain: 'Marketing',
      description: 'Optimize website content for search engines.',
    },
    {
      id: 21,
      title: 'Database Administrator',
      company: 'Data Solutions',
      location: 'Sacramento, CA',
      type: 'Full-Time',
      domain: 'IT',
      description: 'Manage and maintain database systems.',
    },
    {
      id: 22,
      title: 'Mobile App Developer',
      company: 'App Creators',
      location: 'Las Vegas, NV',
      type: 'Full-Time',
      domain: 'Software Development',
      description: 'Develop and maintain mobile applications.',
    },
    {
      id: 23,
      title: 'Legal Assistant',
      company: 'Legal Experts',
      location: 'New Orleans, LA',
      type: 'Full-Time',
      domain: 'Legal',
      description: 'Assist with legal research and documentation.',
    },
    {
      id: 24,
      title: 'Research Scientist',
      company: 'Research Lab',
      location: 'Cleveland, OH',
      type: 'Full-Time',
      domain: 'Research',
      description: 'Conduct scientific research and experiments.',
    },
    {
      id: 25,
      title: 'Electrical Engineer',
      company: 'Engineering Solutions',
      location: 'Kansas City, MO',
      type: 'Full-Time',
      domain: 'Engineering',
      description: 'Design and develop electrical systems.',
    },
    {
      id: 26,
      title: 'Mechanical Engineer',
      company: 'Tech Engineers',
      location: 'Salt Lake City, UT',
      type: 'Full-Time',
      domain: 'Engineering',
      description: 'Design and develop mechanical systems.',
    },
    {
      id: 27,
      title: 'Civil Engineer',
      company: 'BuildCo',
      location: 'Indianapolis, IN',
      type: 'Full-Time',
      domain: 'Engineering',
      description: 'Design and oversee construction projects.',
    },
    {
      id: 28,
      title: 'Web Developer',
      company: 'Web Solutions',
      location: 'Columbus, OH',
      type: 'Full-Time',
      domain: 'Software Development',
      description: 'Develop and maintain websites and web applications.',
    },
    {
      id: 29,
      title: 'Systems Analyst',
      company: 'Tech Analysts',
      location: 'Baltimore, MD',
      type: 'Full-Time',
      domain: 'IT',
      description: 'Analyze and improve IT systems.',
    },
    {
      id: 30,
      title: 'Supply Chain Manager',
      company: 'Supply Solutions',
      location: 'Memphis, TN',
      type: 'Full-Time',
      domain: 'Logistics',
      description: 'Manage supply chain operations.',
    },
    {
      id: 31,
      title: 'Biologist',
      company: 'BioTech',
      location: 'Raleigh, NC',
      type: 'Full-Time',
      domain: 'Biology',
      description: 'Conduct biological research and experiments.',
    },
    {
      id: 32,
      title: 'Accountant',
      company: 'Finance Corp',
      location: 'Nashville, TN',
      type: 'Full-Time',
      domain: 'Finance',
      description: 'Manage financial records and prepare reports.',
    },
    {
      id: 33,
      title: 'Chemist',
      company: 'ChemTech',
      location: 'Oklahoma City, OK',
      type: 'Full-Time',
      domain: 'Chemistry',
      description: 'Conduct chemical research and experiments.',
    },
    {
      id: 34,
      title: 'Environmental Scientist',
      company: 'Eco Solutions',
      location: 'Richmond, VA',
      type: 'Full-Time',
      domain: 'Environmental Science',
      description: 'Study and analyze environmental data.',
    },
    {
      id: 35,
      title: 'Health & Safety Officer',
      company: 'SafeWork',
      location: 'Louisville, KY',
      type: 'Full-Time',
      domain: 'Health & Safety',
      description: 'Ensure workplace health and safety compliance.',
    },
    {
      id: 36,
      title: 'Architect',
      company: 'Design Build',
      location: 'St. Louis, MO',
      type: 'Full-Time',
      domain: 'Architecture',
      description: 'Design and plan building structures.',
    },
    {
      id: 37,
      title: 'Mechanical Technician',
      company: 'TechFix',
      location: 'Milwaukee, WI',
      type: 'Full-Time',
      domain: 'Mechanical',
      description: 'Maintain and repair mechanical systems.',
    },
    {
      id: 38,
      title: 'Pharmacist',
      company: 'HealthPharma',
      location: 'Albuquerque, NM',
      type: 'Full-Time',
      domain: 'Pharmacy',
      description: 'Dispense medications and provide health advice.',
    },
    {
      id: 39,
      title: 'Nurse',
      company: 'HealthCare',
      location: 'Tucson, AZ',
      type: 'Full-Time',
      domain: 'Healthcare',
      description: 'Provide nursing care to patients.',
    },
    {
      id: 40,
      title: 'Physician',
      company: 'Medical Center',
      location: 'Fresno, CA',
      type: 'Full-Time',
      domain: 'Healthcare',
      description: 'Diagnose and treat medical conditions.',
    },
    {
      id: 41,
      title: 'Pharmaceutical Sales Representative',
      company: 'PharmaSales',
      location: 'Mesa, AZ',
      type: 'Full-Time',
      domain: 'Sales',
      description: 'Sell pharmaceutical products to healthcare providers.',
    },
    {
      id: 42,
      title: 'Veterinarian',
      company: 'PetCare',
      location: 'Sacramento, CA',
      type: 'Full-Time',
      domain: 'Veterinary',
      description: 'Provide medical care to animals.',
    },
    {
      id: 43,
      title: 'Teacher',
      company: 'Education First',
      location: 'Long Beach, CA',
      type: 'Full-Time',
      domain: 'Education',
      description: 'Teach and mentor students.',
    },
    {
      id: 44,
      title: 'Mechanical Engineer',
      company: 'Engineering Pros',
      location: 'Oakland, CA',
      type: 'Full-Time',
      domain: 'Engineering',
      description: 'Design and develop mechanical systems.',
    },
    {
      id: 45,
      title: 'Systems Administrator',
      company: 'SysAdmin Solutions',
      location: 'Minneapolis, MN',
      type: 'Full-Time',
      domain: 'IT',
      description: 'Manage and maintain IT systems.',
    },
    {
      id: 46,
      title: 'Real Estate Agent',
      company: 'HomeSales',
      location: 'Tulsa, OK',
      type: 'Full-Time',
      domain: 'Real Estate',
      description: 'Assist clients in buying and selling properties.',
    },
    {
      id: 47,
      title: 'Electrical Technician',
      company: 'ElecFix',
      location: 'Arlington, TX',
      type: 'Full-Time',
      domain: 'Electrical',
      description: 'Maintain and repair electrical systems.',
    },
    {
      id: 48,
      title: 'Plumber',
      company: 'Plumbing Solutions',
      location: 'Newark, NJ',
      type: 'Full-Time',
      domain: 'Plumbing',
      description: 'Install and repair plumbing systems.',
    },
    {
      id: 49,
      title: 'Carpenter',
      company: 'BuildPro',
      location: 'Cincinnati, OH',
      type: 'Full-Time',
      domain: 'Construction',
      description: 'Construct and repair building structures.',
    },
    {
      id: 50,
      title: 'Chef',
      company: 'Gourmet Kitchen',
      location: 'Pittsburgh, PA',
      type: 'Full-Time',
      domain: 'Culinary',
      description: 'Prepare and cook meals in a professional kitchen.',
    },
  ];
  
  export default jobsData;
  